# Generated by Django 4.2.2 on 2023-06-29 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_num', models.IntegerField()),
                ('r_title', models.CharField(max_length=100)),
                ('r_content', models.CharField(max_length=300)),
                ('r_regdate', models.DateTimeField()),
                ('r_modifydate', models.DateTimeField(blank=True, null=True)),
                ('r_hit', models.IntegerField(default=0)),
                ('r_recommend', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Free_Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_num', models.IntegerField()),
                ('b_title', models.CharField(max_length=100)),
                ('b_content', models.CharField(max_length=300)),
                ('b_regdate', models.DateTimeField()),
                ('b_modifydate', models.DateTimeField(blank=True, null=True)),
                ('b_hit', models.IntegerField(default=0)),
                ('b_recommend', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
