# Generated by Django 4.2.2 on 2023-06-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeouljRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('gucd', models.CharField(blank=True, max_length=50, null=True)),
                ('gunm', models.CharField(blank=True, max_length=50, null=True)),
                ('dongcd', models.CharField(blank=True, max_length=50, null=True)),
                ('dongnm', models.CharField(blank=True, max_length=50, null=True)),
                ('distin', models.CharField(blank=True, max_length=30, null=True)),
                ('distinnm', models.CharField(blank=True, max_length=30, null=True)),
                ('bn', models.CharField(blank=True, max_length=50, null=True)),
                ('sbn', models.CharField(blank=True, max_length=50, null=True)),
                ('fl', models.CharField(blank=True, max_length=50, null=True)),
                ('cont', models.CharField(blank=True, max_length=200, null=True)),
                ('distin2', models.CharField(blank=True, max_length=50, null=True)),
                ('spa', models.CharField(blank=True, max_length=100, null=True)),
                ('depos', models.CharField(blank=True, max_length=50, null=True)),
                ('depos2', models.CharField(blank=True, max_length=50, null=True)),
                ('bdnm', models.TextField(blank=True, null=True)),
                ('bdcont', models.CharField(blank=True, max_length=50, null=True)),
                ('bdusa', models.CharField(blank=True, max_length=50, null=True)),
                ('cont2', models.CharField(blank=True, max_length=500, null=True)),
                ('newcont', models.CharField(blank=True, max_length=50, null=True)),
                ('newcont2', models.CharField(blank=True, max_length=20, null=True)),
                ('olddepos', models.CharField(blank=True, max_length=50, null=True)),
                ('olddepos2', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.CharField(blank=True, max_length=300, null=True)),
                ('lng', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'SeouljRent',
            },
        ),
        migrations.CreateModel(
            name='SeoulReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('gucd', models.CharField(blank=True, max_length=50, null=True)),
                ('gunm', models.CharField(blank=True, max_length=50, null=True)),
                ('dongcd', models.CharField(blank=True, max_length=50, null=True)),
                ('dongnm', models.CharField(blank=True, max_length=50, null=True)),
                ('distin', models.CharField(blank=True, max_length=30, null=True)),
                ('distinnm', models.CharField(blank=True, max_length=30, null=True)),
                ('bn', models.CharField(blank=True, max_length=50, null=True)),
                ('sbn', models.CharField(blank=True, max_length=50, null=True)),
                ('bdnm', models.TextField(blank=True, null=True)),
                ('cont', models.CharField(blank=True, max_length=200, null=True)),
                ('depos', models.CharField(blank=True, max_length=50, null=True)),
                ('spa', models.CharField(blank=True, max_length=100, null=True)),
                ('spa2', models.CharField(blank=True, max_length=100, null=True)),
                ('fl', models.CharField(blank=True, max_length=50, null=True)),
                ('authr', models.CharField(blank=True, max_length=50, null=True)),
                ('cancel', models.CharField(blank=True, max_length=50, null=True)),
                ('bdcont', models.CharField(blank=True, max_length=50, null=True)),
                ('bdusa', models.CharField(blank=True, max_length=50, null=True)),
                ('noti', models.CharField(blank=True, max_length=50, null=True)),
                ('notibu', models.CharField(blank=True, max_length=200, null=True)),
                ('lat', models.CharField(blank=True, max_length=300, null=True)),
                ('lng', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'SeoulReal',
            },
        ),
    ]
